logging.file: logs/application.log
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG
spring:
  datasource:
    url:  jdbc:h2:mem:todo
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true