-- INSERT INTO parking_lot(`name`,`capacity`,`location`) VALUES ('panda', 10, 'south');
-- INSERT INTO parking_lot(`name`,`capacity`,`location`) VALUES ('eric', 11, 'east');
-- INSERT INTO parking_lot(`name`,`capacity`,`location`) VALUES ('bill', 12, 'west');
-- INSERT INTO parking_order(`car_number`,`created_time`,`closed_time`) VALUES ('粤A123456', current_timestamp(), CURRENT_TIMESTAMP());
-- INSERT INTO parking_order(`car_number`,`created_time`,`closed_time`) VALUES ('粤B123456', current_timestamp(), CURRENT_TIMESTAMP());
-- INSERT INTO parking_order(`car_number`,`created_time`,`closed_time`) VALUES ('粤C123456', current_timestamp(), CURRENT_TIMESTAMP());